; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:cardputer-adv]
platform = espressif32@6.9.0
board = esp32-s3-devkitc-1
board_build.flash_size = 8MB
board_build.partitions = partitions_8MB.csv
board_upload.flash_size = 8MB
framework = arduino
monitor_speed = 115200
custom_firmware_name = cardputer-chess
custom_firmware_version = 0.19.0
extra_scripts =
    pre:convert_sprites.py
    pre:inject_version.py
    post:post_build.py
build_flags =
    -DCARDGFX_USE_PSRAM=0
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_LOOP_STACK_SIZE=32768
lib_deps =
    m5stack/M5Unified@0.2.10
    m5stack/M5Cardputer@1.1.1
    m5stack/M5GFX@0.2.16
